# Generated by Django 3.2 on 2021-05-25 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='culture_info',
            fields=[
                ('subtype_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subtype_info', models.CharField(max_length=30, null=True)),
                ('first_culture', models.DateField(blank=True, null=True, verbose_name='First Passage')),
                ('culture_status', models.CharField(blank=True, max_length=40, null=True)),
                ('passage', models.CharField(blank=True, max_length=30, null=True)),
                ('defrozen_passage', models.CharField(blank=True, max_length=40, null=True)),
                ('media', models.CharField(blank=True, max_length=30, null=True)),
                ('tumor_type', models.CharField(blank=True, max_length=30, null=True)),
                ('culture_type', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
                ('last_culture', models.DateField(blank=True, null=True, verbose_name='Last Passage')),
                ('cell_block', models.CharField(blank=True, max_length=30, null=True)),
                ('known_mutation', models.CharField(blank=True, max_length=30, null=True)),
                ('molecular_order_number', models.CharField(blank=True, max_length=10, null=True)),
                ('patient_consent', models.CharField(blank=True, max_length=30, null=True)),
                ('date_consent', models.DateField(blank=True, null=True, verbose_name='Date of Consent')),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
                ('note_2', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='samples',
            fields=[
                ('sample_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sample_name', models.CharField(blank=True, max_length=50, null=True)),
                ('organ', models.CharField(blank=True, max_length=40, null=True)),
                ('tumor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('additional', models.CharField(blank=True, max_length=40, null=True)),
                ('molecular_general', models.CharField(blank=True, max_length=40, null=True)),
                ('molecular_organoid', models.CharField(blank=True, max_length=40, null=True)),
                ('general_consent', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tissue',
            fields=[
                ('tissue_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Tissue_id')),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.samples')),
            ],
        ),
        migrations.CreateModel(
            name='processing',
            fields=[
                ('processing_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tumor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('passage_date', models.DateField(blank=True, null=True)),
                ('media', models.CharField(blank=True, max_length=40, null=True)),
                ('passage_number', models.CharField(blank=True, max_length=30, null=True)),
                ('defrozen_passage', models.CharField(blank=True, max_length=30, null=True)),
                ('status_passage', models.CharField(blank=True, max_length=50, null=True)),
                ('format_processing', models.CharField(blank=True, max_length=50, null=True)),
                ('culture_type', models.CharField(max_length=40, null=True)),
                ('format_number', models.CharField(max_length=40, null=True)),
                ('cell_block', models.CharField(max_length=40, null=True)),
                ('smear', models.CharField(max_length=40, null=True)),
                ('date_block', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('subtype_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.culture_info')),
            ],
        ),
        migrations.CreateModel(
            name='patient_info',
            fields=[
                ('patient_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(max_length=40, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('tissue_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.tissue')),
            ],
        ),
        migrations.CreateModel(
            name='mutations',
            fields=[
                ('mutation_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(max_length=30, null=True)),
                ('chromosome', models.CharField(max_length=10, null=True)),
                ('chromosome_position', models.IntegerField(null=True)),
                ('gene_position', models.IntegerField(null=True)),
                ('protein_position', models.IntegerField(null=True)),
                ('subtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.culture_info')),
            ],
        ),
        migrations.CreateModel(
            name='molecular_order',
            fields=[
                ('molecular_order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('molecular_order_number', models.CharField(max_length=30, null=True)),
                ('assay_type', models.CharField(max_length=30, null=True)),
                ('subtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.culture_info')),
            ],
        ),
        migrations.CreateModel(
            name='freezing_passage',
            fields=[
                ('freezing_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('type_freezing', models.CharField(max_length=40, null=True)),
                ('defrozen_passage', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('passage_number', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('freezing_type', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
                ('tower', models.CharField(max_length=30, null=True)),
                ('box', models.CharField(max_length=40, null=True)),
                ('start', models.CharField(max_length=40, null=True)),
                ('end', models.CharField(max_length=40, null=True)),
                ('frozen_by', models.CharField(max_length=40, null=True)),
                ('vials_removed', models.CharField(max_length=40, null=True)),
                ('date_removed', models.DateTimeField(null=True)),
                ('box_removed', models.CharField(max_length=40, null=True)),
                ('start_removed', models.CharField(max_length=40, null=True)),
                ('end_removed', models.CharField(max_length=40, null=True)),
                ('removed_by', models.CharField(max_length=40, null=True)),
                ('sent_to', models.CharField(max_length=40, null=True)),
                ('processing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.processing')),
            ],
        ),
        migrations.CreateModel(
            name='freezing',
            fields=[
                ('freezing_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('type_freezing', models.CharField(max_length=40, null=True)),
                ('defrozen_passage', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('passage_number', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('freezing_type', models.CharField(blank=True, max_length=40, null=True)),
                ('location', models.CharField(max_length=40, null=True)),
                ('tower', models.CharField(max_length=30, null=True)),
                ('box', models.CharField(max_length=40, null=True)),
                ('start', models.CharField(max_length=40, null=True)),
                ('end', models.CharField(max_length=40, null=True)),
                ('frozen_by', models.CharField(max_length=40, null=True)),
                ('vials_removed', models.CharField(max_length=40, null=True)),
                ('date_removed', models.DateTimeField(null=True)),
                ('box_removed', models.CharField(max_length=40, null=True)),
                ('start_removed', models.CharField(max_length=40, null=True)),
                ('end_removed', models.CharField(max_length=40, null=True)),
                ('removed_by', models.CharField(max_length=40, null=True)),
                ('sent_to', models.CharField(max_length=40, null=True)),
                ('subtype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.culture_info')),
            ],
        ),
        migrations.AddField(
            model_name='culture_info',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.samples'),
        ),
        migrations.CreateModel(
            name='biobank',
            fields=[
                ('biobankID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tissueID', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.tissue')),
            ],
        ),
    ]
