# Generated by Django 3.2 on 2021-05-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210528_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezing_conn',
            name='processing_id',
        ),
        migrations.RemoveField(
            model_name='freezing_conn',
            name='subtype_id',
        ),
        migrations.AddField(
            model_name='freezing_conn',
            name='data_of_ids',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
