# Generated by Django 3.2 on 2021-05-31 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210528_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezing',
            name='related_id',
        ),
        migrations.AddField(
            model_name='freezing',
            name='processing_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.processing'),
        ),
        migrations.AddField(
            model_name='freezing',
            name='subtype_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.culture_info'),
        ),
    ]
