# Generated by Django 3.2 on 2021-05-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210531_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezing',
            name='amount',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='freezing',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezing',
            name='date_removed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezing',
            name='defrozen_passage',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='freezing',
            name='passage_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
