# Generated by Django 3.2 on 2021-06-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210531_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='freezing_conn',
        ),
    ]
